//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Data.dbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCentroMedicoContainer : DbContext
    {
        public dbCentroMedicoContainer()
            : base("name=dbCentroMedicoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultorio> Consultorios { get; set; }
        public virtual DbSet<Doctore> Doctores { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<SegurosMedico> SegurosMedicos { get; set; }
        public virtual DbSet<Clinica> Clinicas { get; set; }
    }
}
