//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Data.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public System.Guid GID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Indx { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Identification { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public int Edad { get; set; }
        public System.Guid InsuranceID { get; set; }
    }
}
