//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Data.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegurosMedico
    {
        public System.Guid GID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Indx { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
        public string Type { get; set; }
        public string InsuranceCompany { get; set; }
    }
}
